### ISSUE TITLE
How to cap maximum campaign exposure at execution time and in performance calculations

### ISSUE THREAD

**Issue by nikolas-joyce** [TMQR/SG#25] opened 2019-05-20 20:29 UTC
How to cap maximum campaign exposure at execution time and in performance calculations. We need to be able to cap the maximum exposure to a leverage cap in the campaign setup.

**Comment by alexveden** [comment] 2019-06-25 04:51
Duplicate of #27

**Closed by alexveden** 2019-06-25 04:51 UTC
Labels: duplicate, enhancement
